 //****************************  
 //  Copyright:PERFECT WORLD  
 //  Modified:2012  
 //  Author:???  
 //  TaskName: ????ú??????? 
 //****************************  
function OnDead(){ 
	BC("screen","map",127,"Shadow of the Past - Arch Heretic Britacesk returned to the endless history again!")
	BC("chat","map",127,"Shadow of the Past - Arch Heretic Britacesk returned to the endless history again!")
} 