del /a/q %CD%\GameServer\*.dmp
del /a/q %CD%\GameServer\*.log
del /a/q %CD%\LocalSaveServer\*.dmp
del /a/q %CD%\GateServer\*.dmp
rd /s/q %CD%\GameServer\log
rd /s/q %CD%\GameServer\gmlog
rd /s/q %CD%\GameServer\chatlog
rd /s/q %CD%\GameServer\explog
rd /s/q %CD%\GameServer\moneylog
rd /s/q %CD%\GameServer\game_customerservicelog
rd /s/q %CD%\GateServer\gatelog
rd /s/q %CD%\LocalSaveServer\log
rd /s/q %CD%\ManagerServer\log
rd /s/q %CD%\ManagerServer\gmlog
rd /s/q %CD%\ShareMemProc\log
rd /s/q %CD%\ManagerServer\manager_customerservicelog
del /a/q %CD%\GateServer\linkdmodule.log
del /a/q D:\output.log
del /a/q D:\cash_backup.data
del /a/q D:\output.log.????-??-??